### LSE Data Analytics Online Career Accelerator

# DA201: Data Analytics using Python

## Practical activity: Create a DataFrame from the dictionary

**This is the start to the activity.**

A peer has come to you for help. They have started building a dictionary using Jupyter Notebook. Below you will find their incomplete code. Now that you have learned to add values and keys using a DataFrame, make changes to the code to complete the following:
- Import the dictionary into a DataFrame and add two more rows to the state and capital columns.
- Sense-check the code that was presented to you is accurate and free from errors.

### Raw data
- states = ["Acre", "Alogoas", "Amapa", "Amazonas", "Bahia", "Ceara", "Distrito Federal", 
            "Espirito Santo", "Goiás", "Maranhao", "Mato grosso", "Mato grosso do sul", 
            "Minas gerais", "Para", "Paraiba", "Parana", "Pernambuco", "Piaui", "Rio de Janeiro", 
            "Rio Grande do norte", "Rio Grande do Sul", "Rondonia", "Roraima", "Santa Catarina", 
            "Sao Paulo", "Sergipe", "Tocantins"]

- capitals = ["Rio Branco", "Maceió" "Macapá", "Manaus", "Salvador", "Fortaleza", "Brasília", 
              "Vitória", "Goiânia", "São Luís", "Cuiabá", "Campo Grande","Belo Horizonte","Belém",
              "João Pessoa", "Curitiba", "Recife", "Teresina", "Rio de Janeiro", "Natal", "Porto Alegre", 
              "Porto Velho", "Boa Vista", "Florianópolis", "São Paulo", "Aracaju", "Palmas"]

### Incomplete Dictionary

In [3]:
import pandas as pd

In [5]:
# Create dictionary
brazil = {'states' : ["Acre", "Alogoas", "Amapa", "Amazonas", "Bahia", "Ceara", "Distrito Federal",
                        "Espirito Santo", "Goiás", "Maranhao", "Mato grosso", "Mato grosso do sul", 
                        "Minas gerais", "Para", "Paraiba", "Parana", "Pernambuco", "Piaui", "Rio de Janeiro", 
                        "Rio Grande do norte", "Rio Grande do Sul", "Rondonia", "Roraima", "Santa Catarina", 
                        "Sao Paulo", "Sergipe", "Tocantins"],
           'capitals' : ["Rio Branco", "Maceió", "Macapá", "Manaus", "Salvador", "Fortaleza", "Brasília", 
                         "Vitória", "Goiânia", "São Luís", "Cuiabá", "Campo Grande","Belo Horizonte","Belém",
                         "João Pessoa", "Curitiba", "Recife", "Teresina", "Rio de Janeiro", "Natal", "Porto Alegre", 
                         "Porto Velho", "Boa Vista", "Florianópolis", "São Paulo", "Aracaju", "Palmas"]}

# Create data frame from dictionary
brazil_fire = pd.DataFrame(brazil)

# View the dataframe
brazil_fire

                 states        capitals
0                  Acre      Rio Branco
1               Alogoas          Maceió
2                 Amapa          Macapá
3              Amazonas          Manaus
4                 Bahia        Salvador
5                 Ceara       Fortaleza
6      Distrito Federal        Brasília
7        Espirito Santo         Vitória
8                 Goiás         Goiânia
9              Maranhao        São Luís
10          Mato grosso          Cuiabá
11   Mato grosso do sul    Campo Grande
12         Minas gerais  Belo Horizonte
13                 Para           Belém
14              Paraiba     João Pessoa
15               Parana        Curitiba
16           Pernambuco          Recife
17                Piaui        Teresina
18       Rio de Janeiro  Rio de Janeiro
19  Rio Grande do norte           Natal
20    Rio Grande do Sul    Porto Alegre
21             Rondonia     Porto Velho
22              Roraima       Boa Vista
23       Santa Catarina   Florianópolis
24            Sao Paulo       São Paulo
25              Sergipe         Aracaju
26            Tocantins          Palmas

In [6]:
# Adding 2 extra states & capital

brazil_extra = {'states' : ["state1", "state2"],
                'capitals' : ["cap1", "cap2"]
               }

brazil_fire_extra = pd.DataFrame(brazil_extra)
brazil_fire_extra

   states capitals
0  state1     cap1
1  state2     cap2

In [7]:
# Concatinating the 2 data frames

brazil_fire_final = pd.concat([brazil_fire, brazil_fire_extra], ignore_index = True)

# View the concatinated dataframe
brazil_fire_final

                 states        capitals
0                  Acre      Rio Branco
1               Alogoas          Maceió
2                 Amapa          Macapá
3              Amazonas          Manaus
4                 Bahia        Salvador
5                 Ceara       Fortaleza
6      Distrito Federal        Brasília
7        Espirito Santo         Vitória
8                 Goiás         Goiânia
9              Maranhao        São Luís
10          Mato grosso          Cuiabá
11   Mato grosso do sul    Campo Grande
12         Minas gerais  Belo Horizonte
13                 Para           Belém
14              Paraiba     João Pessoa
15               Parana        Curitiba
16           Pernambuco          Recife
17                Piaui        Teresina
18       Rio de Janeiro  Rio de Janeiro
19  Rio Grande do norte           Natal
20    Rio Grande do Sul    Porto Alegre
21             Rondonia     Porto Velho
22              Roraima       Boa Vista
23       Santa Catarina   Florianópolis
24            Sao Paulo       São Paulo
25              Sergipe         Aracaju
26            Tocantins          Palmas
27               state1            cap1
28               state2            cap2